server:
  port: 8883

spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://localhost:8888
      username: config
      password: c0nf1g
      enabled: false
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 10000
        multiplier: 1.0
        max-interval: 10000
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    registerWithEureka: true
security:
  jwt:
    urlAuth: /auth/**
    authorization: Authorization
    authorities: authorities
    prefix: Bearer
    expirationMinutes: 15
    secret: JwtS3cre3tk3y123JwtS3cre3tk3y456JwtS3cre3tk3y789JwtS3cre3tk3y012

app:
  db.init: true
