server:
  port: 8881

spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:8888
      username: config
      password: c0nf1g
      enabled: false
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 10000
        multiplier: 1.0
        max-interval: 10000
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      discovery:
        locator:
          enabled: true
  output:
    ansi:
      enabled: always
  http:
    encoding:
      charset: UTF-8
      enabled: true

eureka:
  client:
    registerWithEureka: true

springdoc:
  swagger-ui:
    urls:
      - name: scheduler-service
        url: /v3/api-docs/scheduler-service
