server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    config:
      uri: http://localhost:8888
      username: config
      password: c0nf1g
      enabled: false
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 10000
        multiplier: 1.0
        max-interval: 10000

eureka:
  environment: DEV
  client:
    registerWithEureka: false
    fetchRegistry: false